### ISSUE TITLE
2.0.6 Crashing

### ISSUE THREAD

**Issue by CZonin** [andyvorld/LGSTrayBattery#37]
LGSTrayBattery crashes on hover. I've attached the crashlog.

Let me know if there's any other info I can provide!

[Crashlog.log](https://github.com/andyvorld/LGSTrayBattery/files/9150374/Crashlog.log)

**Comment by paulkilla** [comment]
I also get a crashlog.log but with the following
`System.OperationCanceledException: The operation was canceled.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.OverlappedValueTaskSource.GetResult(Int16 token)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(Memory`1 destination, CancellationToken cancellationToken)
   at Hid.Net.Windows.WindowsHidHandler.ReadReportAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/Windows/WindowsHidHandler.cs:line 174
   at Hid.Net.HidDevice.ReadReportAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 129
   at Hid.Net.HidDevice.ReadAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 121
   at LGSTrayHID.LogiDeviceHandler.WriteReadTimeoutAsync(Byte[] payload, UInt16 timeout) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 205
   at LGSTrayHID.LogiDeviceHandler.GetProtocolAsync(Byte deviceId) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 224
   at LGSTrayHID.LogiDeviceHandler.InitializeHIDPPAsync() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 55
   at LGSTrayHID.LogiDeviceHandler.CreateNewHandler(IDevice device) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 44
   at LGSTrayHID.HIDDeviceManager._deviceListener_DeviceInitialized(Object sender, DeviceEventArgs e) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\HIDDeviceManager.cs:line 71
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
`

**Comment by IPGitUser** [comment]
I am receiving a similar crashlog for both the standard and standalone versions.
[Crashlog.log](https://github.com/andyvorld/LGSTrayBattery/files/9192011/Crashlog.log)

**Comment by andyvorld** [comment]
Try this release
https://github.com/andyvorld/LGSTrayBattery/releases/tag/v2.0.7

**Comment by paulkilla** [comment]
With that release I get:
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LGSTrayGUI.MainWindowViewModel.UpdateSelectedDeviceOnLaunch(Object sender, PropertyChangedEventArgs e) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayGUI\MainWindowViewModel.cs:line 166
   at LGSTrayGUI.MainWindowViewModel.<>c__DisplayClass26_0`1.<RegisterDeviceManager>b__0(Object o, NotifyCollectionChangedEventArgs e) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayGUI\MainWindowViewModel.cs:line 145
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at LGSTrayHID.HIDDeviceManager._deviceListener_DeviceInitialized(Object sender, DeviceEventArgs e) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\HIDDeviceManager.cs:line 86
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by Zenrage** [comment]
I tried the new version, and I constantly get USB disconnections.  I was playing a game and the rescan interval I think is disconnecting my Logi devices.

I use the G502 LS/ G915 Wireless

**Comment by paulkilla** [comment]
I should add I'm using:

- G733
- G915 TKL
- Pro X Superlight

**Comment by wergio** [comment]
crashing for me with 2.0.7. I've G533 headset, Mx Vertical, and other logitech periferals. would be usefull to kwno witch device is causing the crash. two different logs below:

System.NullReferenceException: Object reference not set to an instance of an object.
   at LGSTrayHID.LogiDeviceHandler.GetFeatureIdx(Byte deviceId, UInt16 featureId)
   at LGSTrayHID.LogiDeviceHandler.GetFeatureIdx(Byte deviceId, HIDFeatureID featureID) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 249
   at LGSTrayHID.LogiDeviceHandler.InitializeHIDPPAsync() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 70
   at LGSTrayHID.LogiDeviceHandler.CreateNewHandler(IDevice device) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 44
   at LGSTrayHID.HIDDeviceManager._deviceListener_DeviceInitialized(Object sender, DeviceEventArgs e) in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\HIDDeviceManager.cs:line 71
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()


System.IO.IOException: An error occurred while attempting to write to the device
 ---> Device.Net.Exceptions.NotInitializedException: The device has not been initialized
   at Hid.Net.Windows.WindowsHidHandler.WriteReportAsync(Byte[] data, Byte reportId, CancellationToken cancellationToken) in /_/src/Hid.Net/Windows/WindowsHidHandler.cs:line 191
   at Hid.Net.HidDevice.WriteReportAsync(Byte[] data, Byte reportId, CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 175
   --- End of inner exception stack trace ---
   at Hid.Net.HidDevice.WriteReportAsync(Byte[] data, Byte reportId, CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 179
   at LGSTrayHID.LogiDeviceHandler.UpdateBatteryStatus() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 181
   at LGSTrayHID.LogiDeviceHandler.UpdateBattery() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 168
   at LGSTrayHID.HIDDeviceManager.UpdateDevicesAsync() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayHID\HIDDeviceManager.cs:line 55
   at LGSTrayGUI.MainWindowViewModel.<>c__DisplayClass26_0`1.<<RegisterDeviceManager>b__2>d.MoveNext() in C:\Users\Andrew\source\repos\LGSTrayBattery\LGSTrayGUI\MainWindowViewModel.cs:line 153
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by wergio** [comment]
thanks, now not crashing anymore! 

correctly detected:
Mx Vertical mouse
K360 Keyboard
K400 plus Keyboard

but NOT detected: 
G533 headset wireless

what can i do to make it work even with the headset?

**Comment by andyvorld** [comment]
> 

Could you please redirect further comments to #40?
