### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Logerfo** [andyvorld/LGSTrayBattery#55]
Although I don't have G Hub installed, I have a G935 Wireless Headset connected to my laptop.  I know it's not officially supported, but here's the crash report:

>System.IO.IOException: An error occurred while attempting to read from the device
 ---> Device.Net.Exceptions.NotInitializedException: The device has not been initialized.
   at Hid.Net.Windows.WindowsHidHandler.ReadReportAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/Windows/WindowsHidHandler.cs:line 169
   at Hid.Net.HidDevice.ReadReportAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 129
   --- End of inner exception stack trace ---
   at Hid.Net.HidDevice.ReadReportAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 139
   at Hid.Net.HidDevice.ReadAsync(CancellationToken cancellationToken) in /_/src/Hid.Net/HidDevice.cs:line 121
   at LGSTrayHID.LogiDeviceHandler.WriteReadTimeoutAsync(Byte[] payload, UInt16 timeout) in E:\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 205
   at LGSTrayHID.LogiDeviceHandler.GetFeatureIdx(Byte deviceId, UInt16 featureId) in E:\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 242
   at LGSTrayHID.LogiDeviceHandler.GetFeatureIdx(Byte deviceId, HIDFeatureID featureID) in E:\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 249
   at LGSTrayHID.LogiDeviceHandler.InitializeHIDPPAsync() in E:\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 70
   at LGSTrayHID.LogiDeviceHandler.CreateNewHandler(IDevice device) in E:\repos\LGSTrayBattery\LGSTrayHID\LogiDeviceHandler.cs:line 44
   at LGSTrayHID.HIDDeviceManager._deviceListener_DeviceInitialized(Object sender, DeviceEventArgs e) in E:\repos\LGSTrayBattery\LGSTrayHID\HIDDeviceManager.cs:line 71
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

```ini
[HTTPServer]
serverEnable = true
tcpPort = 12321
tcpAddr = 127.0.0.1

[DeviceManager]
GHUB = false
HID_NET = true
Native = true
```

**Comment by andyvorld** [comment]
The exception is due the .net implementation of the library. Disable it with `HID_NET = false` in the settings

**Comment by Logerfo** [comment]
No more exceptions, but the device cannot be found either way. I think the G935 is "officially unsupported" :(
